name: credit_pulse
version: "1.0.0"
config-version: 2

profile: credit_pulse

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  credit_pulse:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
